### ISSUE TITLE
warning: field is never read

### ISSUE THREAD

**Issue by etaylor77** [countercept/chainsaw#66]
Running Ubuntu 20.04 and getting the following errors when launching cargo build

`warning: field is never read: `category`
  --> src/convert/sigma.rs:22:5
   |
22 |     pub category: Option<String>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `product`
  --> src/convert/sigma.rs:24:5
   |
24 |     pub product: Option<String>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `service`
  --> src/convert/sigma.rs:26:5
   |
26 |     pub service: Option<String>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `logsource`
  --> src/convert/sigma.rs:50:5
   |
50 |     pub logsource: Option<LogSource>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `chainsaw` (lib) generated 4 warnings
    Finished release [optimized] target(s) in 3m 30s
`

**Comment by FranticTyping** [comment]
Hi @etaylor77,

These are just warnings and not errors. They're only there because there are a few fields that are declared but not used, it won't impact the tool. 

The compiled binary will still be available in the release section. 

I'll probably remove these in the next release, but it's a non-issue imo.
