### ISSUE TITLE
Sigma.csv Formatting

### ISSUE THREAD

**Issue by b1draper** [countercept/chainsaw#89]
In version 2.0.0-beta.2 - There appears to be a formatting issue with the sigma.csv file. In the "Event Data" column the data appears as blank or as "---" due to formatting and a few carriage returns. When processing the same data with the older version 1.1.7 the formatting issue didn't show up since I believe that the "sigma.csv" might be a new report
<p>
<b>Example Showing how it displays in Timeline Explorer:</b>
![image](https://user-images.githubusercontent.com/44442120/180433261-8b83c62f-0d1b-4281-b80d-34d37d18b6f5.png)
<p>
<b>Example showing copy of sanitized data within one of the rows in that column:</b>
![image](https://user-images.githubusercontent.com/44442120/180433850-0601dac7-7291-431b-b79b-5fbf94859095.png)

**Comment by alexkornitzer** [comment]
Hi @b1draper,

They come in for me but with the `sigma-event-logs-all` mapping the `EventData` is stored as a YAML string. Thus my assumption here is that the tool you are using in the above has not expanded the cell to show you all of its contents, or it is not handling carriage returns within strings correctly.

<img width="692" alt="Screenshot 2022-07-22 at 14 48 45" src="https://user-images.githubusercontent.com/2750747/180453440-9d2d6285-abfe-4c29-9a2e-fd581daf9e18.png">

What tool are you using, then I could have a look, or maybe we need to change the EventData output format for CSV?

**Comment by b1draper** [comment]
Hello Alex,

Thanks for getting back to me so quickly. I'm viewing the CSV file using
Eric Zimmerman's Timeline Explorer. I imagine that if I viewed the files
within Excel it would probably be ok. But Timeline Explorer is a DFIR
mainstay and handles large files really well. The syntax I'm using is as
follows.
./chainsaw hunt /mnt/h/Customer/FS1/export/eventlogs/ --mapping
./mappings/sigma-event-logs-all.yml --sigma ./sigma/rules/ -r ./rules/
--csv --output /mnt/h/customer/FS1/export/newchainsawtest2/

Thanks for the help,

Brian

**Comment by alexkornitzer** [comment]
No worries,

Right so I just tried it and the data is there, if you hover or double click on the cell it will show the full contents. I can't see a way to expand the cell height, so it might be worth putting that in as a feature request to Timeline Explorer?

I am not sure if its worth changing Chainsaw side as the data is more readable in this format, but am very open to suggestions. We could potentially flatten out the YAML.

**Comment by EricZimmerman** [comment]
it already does that. if there are CRLFs and whatnot, the rows expand. to see this, dump an MFT to csv and load it, then look in the Zone id column and you will see how the data shows up.

there does not seem to be anything to do here. if there are CRLFs and the CSV is properly formatted, TLE will expand the rows.

![image](https://user-images.githubusercontent.com/4265254/180479225-c156c6bc-806f-41be-b746-154ae06fe73a.png)


![image](https://user-images.githubusercontent.com/4265254/180479239-5dd4a36e-c7f4-4e6e-9fa7-c581978a4e52.png)

**Comment by alexkornitzer** [comment]
@EricZimmerman, thanks for the clarification and example, super helpful. In that case I have a feeling then it is because Chainsaw is only using `\n` and not doing CRLF. I will dig into it now.

**Comment by alexkornitzer** [comment]
Hi @EricZimmerman, 

I must be doing something incredibly wrong because even with a very basic CSV I cannot get Timeline Explorer (1.3 or 2.0) to expand the row. I can tell it has parsed it correctly because the tooltip and the cell view both recognise the line break and format it correctly. Do you have any thoughts as to what I could be doing wrong here?

<img width="168" alt="Screenshot 2022-07-22 at 22 48 00" src="https://user-images.githubusercontent.com/2750747/180573440-03a08dcc-a225-4b2d-8450-5ef70362cac2.png">
<img width="243" alt="Screenshot 2022-07-22 at 22 47 22" src="https://user-images.githubusercontent.com/2750747/180573441-be49296d-a577-4e8f-ab49-fccbce71d716.png">
<img width="449" alt="Screenshot 2022-07-22 at 22 47 36" src="https://user-images.githubusercontent.com/2750747/180573437-a5e2f66b-d1ef-4b68-96d5-d4e4884101b7.png">

**Comment by EricZimmerman** [comment]
What does it do in 2.0?

I don't see why it would not work

**Comment by alexkornitzer** [comment]
2.0 is displaying it in exactly the same way as 1.3 for me.

**Comment by alexkornitzer** [comment]
Okay I have worked it out, Timeline Explorer is only enabling multiline support if `Zone` is in the column name hence the cells not being expanded. I am going to close this issue out as it is not a Chainsaw bug.

<img width="375" alt="Screenshot 2022-07-23 at 12 18 16" src="https://user-images.githubusercontent.com/2750747/180602840-21e7aa9d-350c-49cd-bf1b-e0a4fc2e3814.png">
<img width="389" alt="Screenshot 2022-07-23 at 12 16 39" src="https://user-images.githubusercontent.com/2750747/180602842-dfe70f32-6130-4fab-8af0-f01ebb243a61.png">

**Comment by EricZimmerman** [comment]
Ah okay so in that case simply creating a plugin to support chainsaw for timeline explorer would solve this issue on all fronts and any other format

**Comment by b1draper** [comment]
Guys,

Thanks for working on this.

**Comment by FranticTyping** [comment]
I would maybe suggest making a toggle option for Timeline Explorer to expand the column as opposed to a plugin specifically for Chainsaw? Otherwise there would likely need to be a plugin for each CSV format moving forwards, as opposed to one generic solution.

Either way, it sounds like we have identified that the support needs to be added on the TimelineExplorer side for this issue. Thanks for everyone's work figuring this out! 👍

**Comment by alexkornitzer** [comment]
Additionally @b1draper if you just wanna view the data now and not wait for changes if you add `Zone` into the name for Event Data field this will trick TE into using multiline.

**Comment by EricZimmerman** [comment]
That suggestion won't work because I would have to make every single field a particular type of editor

It's trivial to make a new plugin for CSV formats that are going to be used a lot which is the right approach anyway because it gives you strongly type data versus treating everything as strings

I could certainly add another line like currently exists where it looks for the string multi and enables such a feature which then makes it dynamic based on the column header

**Comment by b1draper** [comment]
Good Morning Eric,

The work around that Alex mentioned works but (but it is not very easy for
me to articulate to other analysts that I know). I was curious if you're
still planning on writing the plug-in for the chainsaw sigma.csv file?

Thanks for your help

**Comment by EricZimmerman** [comment]
i wasnt planning on it, but the plugins are open source. anyone can write it. you may be able to convince andrew to write a plugin for it, but i would have to tweak things in TLE proper to detect the column that has multiple lines.

its a tricky problem to balance. the plugin is easy, the second part is more difficult
